<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Mvc" Version="8.0.0" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" Version="8.0.0" />
		<PackageReference Include="AspNetCore.HealthChecks.MongoDb" Version="8.0.0" />
		<PackageReference Include="AspNetCore.HealthChecks.Redis" Version="8.0.0" />
		<PackageReference Include="AspNetCore.HealthChecks.SqlServer" Version="8.0.0" />
		<PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="8.0.0" />
		<PackageReference Include="MassTransit" Version="9.1.2" />
		<PackageReference Include="MassTransit.RabbitMQ" Version="9.1.2" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.4">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="8.0.4" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\..\..\Shared\Queries\Domain\MoviesRental.Query.Domain\MoviesRental.Query.Domain.csproj" />
		<ProjectReference Include="..\..\..\..\Shared\Queries\Infrastructure\MoviesRental.Query.Infrastructure\MoviesRental.Query.Infrastructure.csproj" />
		<ProjectReference Include="..\..\Infrastructure\MoviesRental.Infrastructure\MoviesRental.Infrastructure.csproj" />
	</ItemGroup>
</Project>